import { StyleSheet } from 'react-native';
import variables from '../../assets/styles/variables';

const styles = StyleSheet.create({
    wrapperListResult1: {
        width: '90%',
        position: 'absolute',
        top: 60,
    },
    mainTitle: {
        fontWeight: '700',
        fontSize: 18,
        lineHeight: 23,
        textAlign: 'left',
        color: '#303030',
        fontFamily: variables.nunito400,
        marginBottom: 20,
    },
    itemResultDrillDown: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        minHeight: 64,
        display: 'flex',
        flexDirection: 'row',
        flexWrap: 'wrap',
        borderWidth: 0.2,
        borderColor: 'rgba(40, 90, 132, 0.1);',
        borderRadius: 2,
        marginBottom: 15,
        width: variables.screenWidth * 0.9,
        backgroundColor: variables.whiteColor,
        marginTop: 10,
        shadowColor: 'rgba(40, 90, 132, 0.4)',
        shadowOffset: {
            width: 0,
            height: 8,
        },
        shadowRadius: 4,
        shadowOpacity: 0.2,
        elevation: 2,
    },
    itemResultDrillDownColumnTitle: {
        display: 'flex',
        flexDirection: 'column',
        marginTop: 10,
        width: '90%',
    },
    itemResultDrillDownColumnIcon: {
        alignItems: 'flex-end',
        marginTop: 10,
    },
    itemFilterRow: {
        paddingVertical: 10,
        paddingHorizontal: 16,
        height: 64,
        flexDirection: 'row',
        borderWidth: 0,
        borderRadius: 2,
        marginBottom: 7,
        width: '90%',
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
    },
    itemFilterRowText: {
        fontWeight: '400',
        fontSize: 16,
        lineHeight: 22,
        textAlign: 'left',
        color: '#000000',
        fontFamily: variables.nunito400,
    },
    itemResultSelected: {
        borderWidth: 2,
    },
    column: {
        width: '30%',
    },
    column1: {
        width: '75%',
        alignItems: 'flex-end',
    },
    column2: {
        width: '5%',
        alignItems: 'flex-end',
        padding: 2,
        // flexBasis: '70%',
        // alignItems: 'flex-end',
        // justifyContent: 'center',
    },
    listItemTitle1: {
        fontFamily: variables.nunito400,
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 16,
        display: 'flex',
        alignItems: 'center',
        color: '#285A84',
    },
    listItemSubTitle: {
        fontFamily: variables.nunito400,
        fontWeight: '400',
        fontSize: 16,
        lineHeight: 22,
        alignItems: 'center',
        color: '#285A84',
    },
    listItemSubTitleSelected: {
        color: '#6686A0',
        fontWeight: '900',
    },
    circle: {
        borderWidth: 1,
        borderColor: '#285A84',
        width: 20,
        height: 20,
        borderRadius: 20,
    },
    circleSelected: {
        borderWidth: 5,
    },
    selectedFilterText: {
        color: variables.brandBlueColor,
        fontFamily: variables.nunito400,
        fontWeight: '700',
        fontSize: 14,
        lineHeight: 19,
        marginRight: 7,
    },
    subTitle: {
        fontFamily: variables.nunito400,
        fontWeight: '400',
        fontSize: 10,
        lineHeight: 11,
        color: '#6686A0',
        marginTop: 2,
        marginBottom: 5,
        marginRight: 5,
    },
    customBox: {
        marginTop: 10,
    },
    customHeading: {
        fontFamily: variables.nunito400,
        fontWeight: '400',
        fontSize: 12,
        lineHeight: 16,
        color: variables.brandBlueColor,
    },
    customBoxSize: {
        marginTop: 15,
        display: 'flex',
        flexDirection: 'row',
        marginBottom: 15,
    },
    inputStyle: {
        borderBottomWidth: 2,
        height: 12,
        borderBottomColor: '#F0F0F0',
        borderRadius: 10,
    },
    customBoxElement: {
        display: 'flex',
        flexDirection: 'row',
        marginRight: 5,
        width: '33%',
    },
});

export default styles;
